[phases.setup]
nixPkgs = ["python39", "gcc", "python39Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python eva.py" 